### ISSUE TITLE
IMPORTANT: Licence change

### ISSUE THREAD

**Issue by isedwards** [opencdms/surface#136]
Unlike the OpenCDMS Reference Implementation, SURFACE is not a reusable library but rather a complete solution that is not intended for reuse in other systems. The team would therefore like to ensure that anyone making improvements to the SURFACE software release their changes as open source.

We would therefore like to change the licence to reflect this.

Are all contributors happy with the licence changing from the very permissive MIT open source licence (which basically allows anyone to do anything they like with the software) to GPL3 (the most common and recognised license for when modifications to the software must also be shared)?

**Comment by scottylad501** [comment]
Yes @isedwards please go ahead and make the change. How do we go about making that change?
