### ISSUE TITLE
Upgrade CDK editor to remove warning

### ISSUE THREAD

**Issue by fabiosato** [opencdms/surface#159]
The following alert is begin displayed in the maintenance report editing page:
<img width="323" alt="Screenshot 2024-10-15 at 16 55 00" src="https://github.com/user-attachments/assets/77b25c7e-5d09-4b1c-b031-bdec12cce79a">

Find the references such as in https://github.com/opencdms/surface/blob/main/api/wx/templates/wx/maintenance_reports/new_report.html#L2C1-L3C1 and change the version number to 4.25.0 as suggested.

**Comment by AbnerBissolli** [comment]
[CKEditor 4 LTS (4.23.0 and above) requires Software License Agreement](https://ckeditor.com/docs/ckeditor4/latest/support/licensing/license-and-legal.html), similar issues can be seen in the [django-ckeditor repository](https://github.com/django-ckeditor/django-ckeditor/issues/761), [ckeditor4 repository](https://github.com/ckeditor/ckeditor4/issues/5519) and [ckeditor4-vue repository](https://github.com/ckeditor/ckeditor4-vue/issues/162)

**Comment by fabiosato** [comment]
Fixes have been deployed to the cloud server
