### ISSUE TITLE
Migration to Cloud Server

### ISSUE THREAD

**Issue by scottylad501** [opencdms/surface#19]
Should host SURFACE CDMS in cloud as main or backup for local(Belize) installation. Check cost and feasibility.

**Comment by isedwards** [comment]
We can assist with anything that you need for demonstrations/prototypes on Amazon Web Services. Once we're certain about the cloud services required it's possible we may also be able to find funding to help run the software in production as well.

@fabiosato could you let us know what cloud services would be needed for a full deployment of SURFACE?  Do you tend to just use virtual machines - or would prefer to use kubernetes?

**Comment by AbnerBissolli** [comment]
The develop branch was installed on the cloud service, adding the data necessary for the following stations: Blue Creek, Golden Stream, and Corazon.
